# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creates_time',
            new_name='created_time',
        ),
    ]
